language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
  - php: 7.2
  - php: nightly
  
env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""
    #- LARAVEL_VERSION="5.4.*"
    #- LARAVEL_VERSION="5.5.*"
    #- LARAVEL_VERSION="5.6.*"
  
## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  #- travis_retry composer require illuminate/support:${LARAVEL_VERSION} --no-update
  #- travis_retry composer require illuminate/database:${LARAVEL_VERSION} --no-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - composer dumpautoload -o
   
script:
    - php-cs-fixer fix .
    - phpunit
